### ISSUE TITLE
Use $GOPATH instead of hardcoded path

### ISSUE THREAD

**Issue by montanaflynn** [diadata-org/api-golang#50]
In [exchange-scrapers/cmd/scraper.go#L55-L56](https://github.com/diadata-org/api-golang/blob/master/exchange-scrapers/cmd/scraper.go#L55-L56) there is a hardcoded path which will not work for everyone, I modified it to use the `$GOPATH` environment variable instead. 

```go
configFile := os.Getenv("GOPATH") + "/src/github.com/diadata-org/api-golang/exchange-scrapers/config/exchange-scrapers.json"
```

Maybe it should be set by a flag if `$GOPATH` is not set which may be the future of Go as [module support](https://golang.org/doc/go1.11#modules) becomes more commonplace.

**Comment by frranck** [comment]
Yes we should to move to vgo, that's quite hacky atm

**Comment by montanaflynn** [comment]
I think using `$GOPATH` is an improvement even before modules.
